github:
  prebuilds:
    master: true
    branches: true

ports:
  - port: 8000
    onOpen: open-browser
    visibility: private

image: ghcr.io/kohanyirobert/gitpod-workspace-cv:latest@sha256:aed5951f3479aae7ead43fcb1d5628d47c907e95db6ba967e99735247b1e4067

tasks:
  - name: Build pdf
    command: ./build.sh
    openMode: tab-after
  - name: Serve pdf
    command: ./serve.sh
    openMode: tab-after
