name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - Dockerfile
  push:
    branches:
      - main
    paths-ignore:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build PDF
        uses: docker://ghcr.io/kohanyirobert/cv:latest
        with:
          args: latexmk -quiet -pdflua main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: main.pdf
