name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - Dockerfile
  push:
    branches:
      - main
    paths-ignore:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      download-url: ${{ steps.upload-pdf.outputs.download-url }}
      release-tag: ${{ steps.upload-pdf.outputs.release-tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: docker://ghcr.io/kohanyirobert/cv:latest
        with:
          args: latexmk -quiet -pdflua main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: main.pdf

      - name: Upload PDF to temporary release
        if: github.event_name == 'pull_request'
        id: upload-pdf
        run: |
          # Create a temporary release for PR
          RELEASE_TAG="pr-${{ github.event.pull_request.number }}-$(date +%Y%m%d-%H%M%S)"
          gh release create "$RELEASE_TAG" main.pdf \
            --title "PR #${{ github.event.pull_request.number }} - PDF preview" \
            --notes "Temporary release for PR preview. Will be deleted automatically when PR is closed." \
            --prerelease

          # Get the download URL
          DOWNLOAD_URL=$(gh release view "$RELEASE_TAG" --json assets --jq '.assets[0].url')
          echo "download-url=$DOWNLOAD_URL" >> $GITHUB_OUTPUT
          echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  comment:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Find PDF build comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- pdf-build-comment -->'

      - name: Update PDF comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## 📄 PDF Build Complete

            [Download](${{ needs.build.outputs.download-url }}).

            > Deleted automatically when the PR is closed.

            <!-- pdf-build-comment -->
