name: Build and push CV

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - main.tex

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build PDF
        uses: docker://ghcr.io/kohanyirobert/cv:latest@sha256:3f344f1164a3524855813f70459403f6b6b443b55b6bc27ed3589311a40b3fed
        with:
          args: latexmk -cd -f -interaction=batchmode -pdflua -view=none main.tex

      - name: Configure Git user
        uses: fregante/setup-git-user@v1

      - name: Commit CV to website
        run: |
          git add main.pdf
          git commit --message 'Update CV'
          git push
