name: Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - Dockerfile
  push:
    branches:
      - main
    paths-ignore:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build PDF
        uses: docker://ghcr.io/kohanyirobert/cv:latest
        with:
          args: latexmk -quiet -pdflua main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: main.pdf

      - name: Link PDF artifact in PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Find built PDF [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
