on:
  push:
    workflow_dispatch:
    branches:
      - main

name: Release Please!

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: cv
