name: Release and publish

on:
  push:
    workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Create release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: cv

  build:
    needs: release
    if: needs.release.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Make GitHub Actions bot the Git user
        uses: fregante/setup-git-user@v1

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build PDF
        uses: docker://ghcr.io/kohanyirobert/cv:latest@sha256:3f344f1164a3524855813f70459403f6b6b443b55b6bc27ed3589311a40b3fed
        with:
          args: latexmk -quiet -pdflua main.tex

      - name: Add PDF to release
        run: gh release upload ${{ needs.release.outputs.tag_name }} main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: main.pdf

  publish:
    needs:
      - release
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.com
          ssh-key: ${{ secrets.WEBSITE_DEPLOY_KEY }}

      # Must be used after the checkout action
      - name: Make GitHub Actions bot the Git user
        uses: fregante/setup-git-user@v1

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: cv
          path: main.pdf

      - name: Commit new PDF into website repo
        run: |
          git add main.pdf
          git commit -m 'chore: update CV to version ${{ needs.release.outputs.tag_name }}'
          git push

